version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: clientes_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./API-Clientes
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_NAME: clientes_api
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres